### ISSUE TITLE
JS errors if jQuery not included in user page

### ISSUE THREAD

**Issue by niconoe** [ovidner/djangocms-markdown#1]
Hi,

I just noticed that opening the editor threw JS errors if  the end-user has not manually included jQuery in its page/template. You can reproduce the error by creating a blank project using `djangocms-installer`.

The error happens at line 22 and 23 of `change_form.html`:

```
minHeight: window.parent.$('.cms_modal-frame').height() - 20,
maxHeight: window.parent.$('.cms_modal-frame').height() - 20
```

It happens because as long as jQuery was not included by the user, `window.parent.$`is undefined. I suggest using instead the jQuery copy provided by the Django-CMS in the `CMS`object, such as:

```
minHeight: window.parent.CMS.$('.cms_modal-frame').height() - 20,
maxHeight: window.parent.CMS.$('.cms_modal-frame').height() - 20
```

I tested on my install and it seems to work fine. I'll submit a pull request in a second.

**Comment by ovidner** [comment]
I didn't even realize someone else used this :) Thanks for the report and the fix!
